apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-learning
  namespace: argocd
spec:
  project: argocd-learning
  source:
    repoURL: https://github.com/nakamuramasataka/argocd-learning.git
    path: kubernetes
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-learning
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true